export const LOAD_JOB_APPLICATIONS = 'LOAD_JOB_APPLICATIONS';
export const ADD_JOB_APPLICATION = 'ADD_JOB_APPLICATION';
export const DELETE_JOB_APPLICATION = 'DELETE_JOB_APPLICATION';
export const EDIT_JOB_APPLICATION = 'EDIT_JOB_APPLICATION';
